CI FIXME: disable arches without openlibm support
Disabled templates are fail to build because openlibm lacks support of
corresponding architecture. In all cases build error starts with:

openlibm_fenv.h:16:2: error: #error "Unsupported platform"
 #error "Unsupported platform"